---
config:
  theme: redux
  look: handDrawn
  fontFamily: '''Inter Variable'', sans-serif'
  themeVariables:
    fontFamily: '''Inter Variable'', sans-serif'
---
stateDiagram
  direction LR
  classDef Sky stroke-width:1px,stroke-dasharray:none,stroke:#374D7C,fill:#E2EBFF,color:#374D7C;
  classDef Ash stroke-width:1px,stroke-dasharray:none,stroke:#999999,fill:#EEEEEE,color:#000000;
  classDef Peach stroke-width:1px,stroke-dasharray:none,stroke:#FBB35A,fill:#FFEFDB,color:#8F632D;
  classDef Aqua stroke-width:1px,stroke-dasharray:none,stroke:#46EDC8,fill:#DEFFF8,color:#378E7A;
  h --> xx
  xx --> x
  x --> s1
  x --> s2
  x --> s3
  s2 --> s4
  s2 --> s5
  s4 --> s6
  s6 --> s7
  s6 --> s8
  s6 --> s9
  s7 --> s10
  s8 --> s10
  s9 --> s10
  s10 --> s26
  s26 --> s11
  s1 --> s12
  s12 --> s27
  s12 --> s28
  s27 --> s26
  s28 --> s13
  s13 --> s14
  s14 --> s15
  s15 --> s10
  s11 --> s16
  s16 --> h
  h --> s17
  s17 --> s18
  s18 --> x
  s3 --> s19
  s19 --> s20
  s19 --> s21
  s20 --> s22
  s22 --> s11
  s21 --> s23
  s23 --> s24
  s24 --> s11
  s5 --> s25
  s25 --> s16
  h:Home Screen
  xx:No account present (5)
  x:Add Account<br>
  s1:Create account
  s2:Import Account (6)
  s3:Add Tangem Card
  s4:Full Access
  s5:Read Only
  s6:Choose Secret Type (7)
  s7:Secret Numbers
  s8:Family Seed
  s9:Mnemonic
  s10:Enter Secret (8)
  s26:Derive
  s11:View derived public address</br>("R-address") - (12)
  s12:Gather Entropy<br>(NATIVE CODE)
  s27:Fast onboarding (10, 11)
  s28:Full onboarding (9)
  s13:Represent Entropy as Secret Numbers
  s14:Show to user (13)
  s15:User has to input the entire secret to confirm
  s16:Add label (name)
  s17:Settings
  s18:Accounts
  s19:Scan card
  s20:No existing wallet on card
  s21:Existing wallet on card
  s22:Ask to create wallet, if so: scan card 10 seconds
  s23:Warn that if user expects card to be new, it isn't: used before, contact support
  s24:Expected
  s25:Import r-address
  class x Sky
  class s12 Ash
  class s6,s10 Peach
  class s11,s14 Aqua
